// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0FdPZgIB2ysD3sE6BXgt8NB8uvcFFzs',
    appId: '1:330573419338:web:4fb38e801466547484a7b3',
    messagingSenderId: '330573419338',
    projectId: 'authtutorial-b1a1c',
    authDomain: 'authtutorial-b1a1c.firebaseapp.com',
    storageBucket: 'authtutorial-b1a1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYBjgJUjINNjKGTUFo4TkIsdF7pU6DjM',
    appId: '1:330573419338:android:5e593ba46c57cfe284a7b3',
    messagingSenderId: '330573419338',
    projectId: 'authtutorial-b1a1c',
    storageBucket: 'authtutorial-b1a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9EmaLq61wCe1SM2O78gHTLSgc4h6570',
    appId: '1:330573419338:ios:8506d59692ab346984a7b3',
    messagingSenderId: '330573419338',
    projectId: 'authtutorial-b1a1c',
    storageBucket: 'authtutorial-b1a1c.appspot.com',
    iosClientId: '330573419338-27krkjops06g8nf80nmlq066ssc8m2b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo9EmaLq61wCe1SM2O78gHTLSgc4h6570',
    appId: '1:330573419338:ios:8506d59692ab346984a7b3',
    messagingSenderId: '330573419338',
    projectId: 'authtutorial-b1a1c',
    storageBucket: 'authtutorial-b1a1c.appspot.com',
    iosClientId: '330573419338-27krkjops06g8nf80nmlq066ssc8m2b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginapp',
  );
}
